// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List website contact leads (name, phone, service, message) for Tamkeen. Requires an admin or staff account.",
  inputSchema: {
    limit: z.number().int().describe("Maximum number of leads to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const { data, error } = await supabaseForUser(ctx).from("leads").select("id, name, phone, email, service, message, source, created_at").order("created_at", { ascending: false }).limit(take);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-financing-requests.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_financing_requests_default = defineTool2({
  name: "list_financing_requests",
  title: "List financing requests",
  description: "List submitted financing requests (applicant, city, salary, obligations, status). Sensitive data: requires an admin or staff account.",
  inputSchema: {
    limit: z2.number().int().describe("Maximum number of requests to return (default 20)."),
    status: z2.string().describe("Optional status filter, e.g. 'new'. Use an empty string for all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("financing_requests").select(
      "id, full_name, phone, email, city, age, monthly_salary, employer, service_years, monthly_obligations, has_existing_financing, has_defaults, property_type, owns_land, status, created_at"
    ).order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { requests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-stats.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var get_stats_default = defineTool3({
  name: "get_pipeline_stats",
  title: "Get pipeline stats",
  description: "Summarize how many leads and financing requests were received in the last N days. Requires an admin or staff account.",
  inputSchema: {
    days: z3.number().int().describe("Look-back window in days (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const window = Math.min(Math.max(days ?? 30, 1), 365);
    const since = new Date(Date.now() - window * 864e5).toISOString();
    const db = supabaseForUser(ctx);
    const [leads, requests] = await Promise.all([
      db.from("leads").select("id", { count: "exact", head: true }).gte("created_at", since),
      db.from("financing_requests").select("id", { count: "exact", head: true }).gte("created_at", since)
    ]);
    const error = leads.error ?? requests.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const stats = {
      days: window,
      leads: leads.count ?? 0,
      financing_requests: requests.count ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/get-service-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var INFO = {
  company: "\u0645\u0643\u062A\u0628 \u062A\u0645\u0643\u064A\u0646 \u0644\u0644\u062D\u0644\u0648\u0644 \u0627\u0644\u062A\u0645\u0648\u064A\u0644\u064A\u0629",
  role: "\u0648\u0633\u064A\u0637 \u062A\u0645\u0648\u064A\u0644\u064A \u0648\u0644\u064A\u0633 \u062C\u0647\u0629 \u062A\u0645\u0648\u064A\u0644 \u0623\u0648 \u0625\u0642\u0631\u0627\u0636 \u0645\u0628\u0627\u0634\u0631\u0629",
  whatsapp: "+966567597514",
  phone: "+966567597514",
  instagram: "https://www.instagram.com/tamkeen_saudi",
  snapchat: "https://www.snapchat.com/add/tamkeen_sa",
  financing_range_sar: { min: 18e3, max: 3e5 },
  max_tenor_months: 60,
  apr_from_percent: 1.5,
  services: [
    "\u0627\u0644\u062A\u0645\u0648\u064A\u0644 \u0627\u0644\u0634\u062E\u0635\u064A",
    "\u0633\u062F\u0627\u062F \u0627\u0644\u0642\u0631\u0648\u0636 \u0627\u0644\u0642\u0627\u0626\u0645\u0629",
    "\u0645\u0639\u0627\u0644\u062C\u0629 \u0627\u0644\u062A\u0639\u062B\u0631\u0627\u062A",
    "\u0625\u0646\u0647\u0627\u0621 \u0625\u064A\u0642\u0627\u0641 \u0627\u0644\u062E\u062F\u0645\u0627\u062A",
    "\u0625\u0639\u0627\u062F\u0629 \u0647\u064A\u0643\u0644\u0629 \u0627\u0644\u0627\u0644\u062A\u0632\u0627\u0645\u0627\u062A"
  ],
  disclaimer: "\u062C\u0645\u064A\u0639 \u0627\u0644\u0637\u0644\u0628\u0627\u062A \u062A\u062E\u0636\u0639 \u0644\u0644\u062A\u062D\u0642\u0642 \u0645\u0646 \u0627\u0644\u0623\u0647\u0644\u064A\u0629\u060C \u0648\u0644\u0627 \u064A\u064F\u0639\u062F \u0642\u0628\u0648\u0644 \u0627\u0644\u0637\u0644\u0628 \u0645\u0648\u0627\u0641\u0642\u0629 \u0639\u0644\u0649 \u0627\u0644\u0625\u0642\u0631\u0627\u0636 \u0623\u0648 \u0627\u0644\u062A\u0645\u0648\u064A\u0644. \u062A\u064F\u062F\u0631\u0633 \u0643\u0644 \u062D\u0627\u0644\u0629 \u0639\u0644\u0649 \u062D\u062F\u0629 \u0648\u0641\u0642 \u0627\u0644\u0634\u0631\u0648\u0637 \u0648\u0627\u0644\u0623\u062D\u0643\u0627\u0645 \u0627\u0644\u0645\u0646\u0638\u0645\u0629\u060C \u0648\u0627\u0644\u062E\u062F\u0645\u0627\u062A \u062A\u062E\u0636\u0639 \u0644\u0631\u0642\u0627\u0628\u0629 \u0648\u0645\u0631\u0627\u062C\u0639\u0629 \u0627\u0644\u062C\u0647\u0627\u062A \u0627\u0644\u0645\u062E\u062A\u0635\u0629 \u0641\u064A \u0627\u0644\u0645\u0645\u0644\u0643\u0629 \u0627\u0644\u0639\u0631\u0628\u064A\u0629 \u0627\u0644\u0633\u0639\u0648\u062F\u064A\u0629."
};
var get_service_info_default = defineTool4({
  name: "get_service_info",
  title: "Get service info",
  description: "Return public information about Tamkeen's financing services, contact channels, and the regulatory disclaimer.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(INFO) }],
    structuredContent: INFO
  })
});

// src/lib/mcp/index.ts
var projectRef = "frmpmfgnveptwieizwob";
var mcp_default = defineMcp({
  name: "tamkeen-mcp",
  title: "Tamkeen Financing MCP",
  version: "0.1.0",
  instructions: "Tools for \u0645\u0643\u062A\u0628 \u062A\u0645\u0643\u064A\u0646 \u0644\u0644\u062D\u0644\u0648\u0644 \u0627\u0644\u062A\u0645\u0648\u064A\u0644\u064A\u0629 (a financing broker in Saudi Arabia). Use `get_service_info` for public service, contact and compliance details. Use `list_leads`, `list_financing_requests` and `get_pipeline_stats` to review submissions \u2014 these require an admin or staff account and return sensitive applicant data, so handle it confidentially.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_service_info_default, list_leads_default, list_financing_requests_default, get_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
